/**
 * Shared utility functions and constants
 */

import profile from '@/data/profile.json';

/**
 * Site configuration.
 *
 * `SITE_URL` is the one place the canonical origin is declared: the sitemap,
 * JSON-LD, and every page's `alternates.canonical` derive from it. To move the
 * site to a custom domain, change this value and add a matching `public/CNAME`
 * — nothing else needs to change.
 *
 * This must be the origin the site is actually *served* from, not the one it
 * is deployed to. `public/CNAME` pointed GitHub Pages at the custom domain
 * while this constant still said `vaibhavjain2609.github.io`, so every
 * canonical, `og:url`, JSON-LD `@id`, and sitemap entry named an origin that
 * 301s to somewhere else — crawlers see a self-referencing canonical pointing
 * off-site, and scrapers fetch the share image through a redirect. Keep this,
 * `public/CNAME`, and `homepage` in `package.json` (which `verify-export`
 * reads as the expected origin) in agreement.
 */
export const SITE_URL = 'https://jainvaibhav.me';
export const AUTHOR_NAME = profile.name;
/**
 * The portrait. Used for JSON-LD `image`, where the value should be a picture
 * of the person, not a designed card.
 */
export const SITE_IMAGE_PATH = '/images/me.jpg';
export const SITE_IMAGE_DIMENSIONS = {
  width: 1200,
  height: 1200,
} as const;

/**
 * The share card, generated by `npm run og` and committed to `public/`.
 *
 * Every page points at this one path explicitly. Next's `opengraph-image`
 * file convention is not used: a route-level `openGraph` object replaces the
 * inherited one wholesale, which left every subpage with no image at all, and
 * the metadata route emits an extensionless file that GitHub Pages serves as
 * application/octet-stream.
 */
export const SHARE_IMAGE_PATH = '/og.png';
export const SHARE_IMAGE_DIMENSIONS = {
  width: 1200,
  height: 630,
} as const;

// Canonical one-line bio, shared across page metadata, OpenGraph, and JSON-LD.
export const SITE_DESCRIPTION =
  'Security engineer and M.Sc. candidate in Digital Forensics and Information Security at NFSU. I break web applications, analyse malware, and build the systems I audit.';

// Image dimension constants
export const PROJECT_IMAGE = {
  width: 600,
  height: 400,
} as const;

// Skill competency
export const MAX_COMPETENCY = 5;

/**
 * Formats a date string to a human-readable format.
 * Parses as UTC to avoid timezone shifts.
 */
export function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  // Parse as UTC to avoid timezone shifts
  const date = new Date(`${dateStr}T12:00:00`);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
